// NAVIAGATION STATUS
export const NAVIGATION_TYPE = "NAVIGATION_TYPE";
export const SHOW_INTRO = "SHOW_INTRO";

// USER LOGOUT
export const USER_LOGOUT = "USER_LOGOUT";

// AUTH ACTIONS

export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const USER_LOGIN_FAILURE = "USER_LOGIN_FAILURE";
export const USER_LOGIN_LOADING = "USER_LOGIN_LOADING";

// AGREE ACTIONS

export const AGREE_SUCCESS = "AGREE_SUCCESS";
export const AGREE_FAILURE = "AGREE_FAILURE";
export const AGREE_LOADING = "AGREE_LOADING";

// FORGOT PASSWORD ACTIONS

export const FORGOTPASSWORD_SUCCESS = "FORGOTPASSWORD_SUCCESS";
export const FORGOTPASSWORD_FAILURE = "FORGOTPASSWORD_FAILURE";
export const FORGOTPASSWORD_LOADING = "FORGOTPASSWORD_LOADING";

// VERIFY FORGOT_PASSWORD CODE ACTIONS

export const VERIFY_CODE_SUCCESS = "VERIFY_CODE_SUCCESS";
export const VERIFY_CODE_FAILURE = "VERIFY_CODE_FAILURE";
export const VERIFY_CODE_LOADING = "VERIFY_CODE_LOADING";

// RESET PASSWORD ACTIONS

export const RESETPASSWORD_SUCCESS = "RESETPASSWORD_SUCCESS";
export const RESETPASSWORD_FAILURE = "RESETPASSWORD_FAILURE";
export const RESETPASSWORD_LOADING = "RESETPASSWORD_LOADING";

// PROFILE INFORMATION ACTIONS

export const PROFILE_INFO_SUCCESS = "PROFILE_INFO_SUCCESS";
export const PROFILE_INFO_FAILURE = "PROFILE_INFO_FAILURE";
export const PROFILE_INFO_LOADING = "PROFILE_INFO_LOADING";

// TOKEN

export const USER_TOKEN = "USER_TOKEN";

// Submit API
export const SURVEY_SUBMIT_TYPE = "SURVEY_SUBMIT_TYPE";

// ASSIGNED TASKS
export const ASSIGNED_TASKS_SUCCESS = "ASSIGNED_TASKS_SUCCESS";
export const ASSIGNED_TASKS_FAILURE = "ASSIGNED_TASKS_FAILURE";
export const ASSIGNED_TASKS_LOADING = "ASSIGNED_TASKS_LOADING";

// ASSIGNED TASK LIST

export const ASSIGNED_TASKS_LIST_SUCCESS = "ASSIGNED_TASKS_LIST_SUCCESS";
export const ASSIGNED_TASKS_LIST_FAILURE = "ASSIGNED_TASKS_LIST_FAILURE";
export const ASSIGNED_LIST_TASKS_LOADING = "ASSIGNED_LIST_TASKS_LOADING";

// SURVEY LIST

export const SURVEY_LIST_SUCCESS = "SURVEY_LIST_SUCCESS";
export const SURVEY_LIST_FAILURE = "SURVEY_LIST_FAILURE";
export const SURVEY_LIST_LOADING = "SURVEY_LIST_LOADING";

// SURVEY DETAILS

export const SURVEY_DETAILS_SUCCESS = "SURVEY_DETAILS_SUCCESS";
export const SURVEY_DETAILS_FAILURE = "SURVEY_DETAILS_FAILURE";
export const SURVEY_DETAILS_LOADING = "SURVEY_DETAILS_LOADING";

// GET QUESTIONS ACTION

export const QUESTIONS_LIST_SUCCESS = "QUESTIONS_LIST_SUCCESS";
export const QUESTIONS_LIST_FAILURE = "QUESTIONS_LIST_FAILURE";
export const QUESTIONS_LIST_LOADING = "QUESTIONS_LIST_LOADING";

// GET LEGAL DOCUMENTATION

export const LEGAL_DOC_SUCCESS = "LEGAL_DOC_SUCCESS";
export const LEGAL_DOC_FAILURE = "LEGAL_DOC_FAILURE";
export const LEGAL_DOC_LOADING = "LEGAL_DOC_LOADING";

// SURVEY INFO INFORMATION

export const SURVEY_INFO = "SURVEY_INFO";

export const HOUSE_HELD_INFO = "HOUSE_HELD_INFO";

// GET SURVEY QUESTIONS A

export const SURVEY_A_QUESTIONS = "SURVEY_A_QUESTIONS";
export const SURVEY_A_QUESTIONS_FAILURE = "SURVEY_A_QUESTIONS_FAILURE";
export const SURVEY_A_QUESTIONS_DATA = "SURVEY_A_QUESTIONS_DATA";
export const SURVEY_A_QUESTIONS_SECTION = "SURVEY_A_QUESTIONS_SECTION";
export const SURVEY_A_QUESTIONS_UPDATE_DATA = "SURVEY_A_QUESTIONS_UPDATE_DATA";

// GET SURVEY QUESTIONS B

export const SURVEY_MEMBERS = "SURVEY_MEMBERS";
export const SURVEY_B_QUESTIONS_DATA = "SURVEY_B_QUESTIONS_DATA";
export const SURVEY_INITIAL_SECTION = "SURVEY_INITIAL_SECTION";
// GET SURVEY QUESTIONS C
export const SURVEY_C_QUESTIONS = "SURVEY_C_QUESTIONS";
export const SURVEY_C_QUESTIONS_FAILURE = "SURVEY_C_QUESTIONS_FAILURE";
export const SURVEY_C_QUESTIONS_DATA = "SURVEY_C_QUESTIONS_DATA";
export const SURVEY_C_QUESTIONS_SECTION = "SURVEY_C_QUESTIONS_SECTION";

export const SURVEY_INPUT_DATA = "SURVEY_INPUT_DATA";
export const SURVEY_NOTES = "SURVEY_NOTES";

export const SURVEY_SIGNATURE = "SURVEY_SIGNATURE";

export const RECORRECTION_SURVEY_NOTES = "RECORRECTION_SURVEY_NOTES";

export const RECORRECTION_SURVEY_SIGNATURE = "RECORRECTION_SURVEY_SIGNATURE";

// RECORRECTION SURVEY INFO INFORMATION

export const RECORRECTION_SURVEY_INFO = "RECORRECTION_SURVEY_INFO";

export const RECORRECTION_HOUSE_HELD_INFO = "RECORRECTION_HOUSE_HELD_INFO";

// GET RECORRECTION_SURVEY QUESTIONS A

export const RECORRECTION_SURVEY_A_QUESTIONS =
  "RECORRECTION_SURVEY_A_QUESTIONS";
export const RECORRECTION_SURVEY_A_QUESTIONS_FAILURE =
  "RECORRECTION_SURVEY_A_QUESTIONS_FAILURE";
export const RECORRECTION_SURVEY_A_QUESTIONS_DATA =
  "RECORRECTION_SURVEY_A_QUESTIONS_DATA";
export const RECORRECTION_SURVEY_OVERALL_DATA =
  "RECORRECTION_SURVEY_OVERALL_DATA";

export const RECORRECTION_SURVEY_A_QUESTIONS_SECTION =
  "RECORRECTION_SURVEY_A_QUESTIONS_SECTION";
export const RECORRECTION_SURVEY_A_QUESTIONS_UPDATE_DATA =
  "RECORRECTION_SURVEY_A_QUESTIONS_UPDATE_DATA";

// GET RECORRECTION_SURVEY QUESTIONS B

export const RECORRECTION_SURVEY_B_QUESTIONS_DATA =
  "RECORRECTION_SURVEY_B_QUESTIONS_DATA";

// GET RECORRECTION_SURVEY QUESTIONS C

export const RECORRECTION_SURVEY_C_QUESTIONS =
  "RECORRECTION_SURVEY_C_QUESTIONS";
export const RECORRECTION_SURVEY_C_QUESTIONS_FAILURE =
  "RECORRECTION_SURVEY_C_QUESTIONS_FAILURE";
export const RECORRECTION_SURVEY_C_QUESTIONS_DATA =
  "RECORRECTION_SURVEY_C_QUESTIONS_DATA";
export const RECORRECTION_SURVEY_C_QUESTIONS_SECTION =
  "RECORRECTION_SURVEY_C_QUESTIONS_SECTION";
export const RECORRECTION_INITIAL_SECTION = "RECORRECTION_INITIAL_SECTION";
export const RECORRECTION_SURVEY_QUESTIONS_FAILURE =
  "RECORRECTION_SURVEY_QUESTIONS_FAILURE";

export const SURVEY_SUBMIT_LOADING = "SURVEY_SUBMIT_LOADING";
export const SURVEY_SUBMIT_SUCESS = "SURVEY_SUBMIT_SUCESS";
export const SURVEY_SUBMIT_FAILURE = "SURVEY_SUBMIT_FAILURE";

export const RECORRECTION_SURVEY_SUBMIT_LOADING =
  "RECORRECTION_SURVEY_SUBMIT_LOADING";
export const RECORRECTION_SURVEY_SUBMIT_SUCESS =
  "RECORRECTION_SURVEY_SUBMIT_SUCESS";
export const RECORRECTION_SURVEY_SUBMIT_FAILURE =
  "RECORRECTION_SURVEY_SUBMIT_FAILURE";

export const TOTAL_HOUSEHOLD_MEMBERS = "TOTAL_HOUSEHOLD_MEMBERS";
// Survey entry id
export const SURVEY_ENTRY_ID = "survey_entry_id";
export const SURVEY_PART_C_DATA = "SURVEY_PART_C_DATA";
//
export const USER_ID = "USER_ID";


// SYNC SURVEY

export const IS_SYNCING = "IS_SYNCING";
export const SYNC_SUCCESS = "SYNC_SUCCESS";
export const INTERNET_LISITENER = "INTERNET_LISITENER";
export const BROADCAST_LISTNER = "BROADCAST_LISTNER";
export const IS_SYNC_LOADING = "IS_SYNC_LOADING";
export const IS_RECORRECTION_SYNC_LOADING = "IS_RECORRECTION_SYNC_LOADING";


// GET ONGOING SURVEY LIST

export const ONGOING_SURVEY_LIST = "ONGOING_SURVEY_LIST";

// NOTIFICATION ACTIONS

export const NOTIFICATION_SUCCESS = "NOTIFICATION_SUCCESS";
export const NOTIFICATION_FAILURE = "NOTIFICATION_FAILURE";
export const NOTIFICATION_LOADING = "NOTIFICATION_LOADING";
export const NOTIFICATION_LOAD_MORE = "NOTIFICATION_LOAD_MORE";
export const NOTIFICATION_CLEAR_ALL = "NOTIFICATION_CLEAR_ALL";
export const NOTIFICATION_CLEAR_ALL_FAILURE = "NOTIFICATION_CLEAR_ALL_FAILURE";
export const NOTIFICATION_CLEAR_ALL_LOADING = "NOTIFICATION_CLEAR_ALL_LOADING";
export const NOTIFICATION_GET_COUNT = "NOTIFICATION_GET_COUNT";
export const NOTIFICATION_SEEN_ALL = "NOTIFICATION_SEEN_ALL";

//DRAWER SURVEY OPTION SHOW/HIDE

export const DRAWER_SURVEY_SHOW = "DRAWER_SURVEY_SHOW";