import Palette from "./palette";

const Colors = {
  transparent: Palette.transparent,
  primaryColor: Palette.white,
  appBackgroundColorPrimary: Palette.white,
  appBackgroundColorSecondary: Palette.app_color,
  black_color: Palette.black,
  fr_grey_color: Palette.fr_grey,
  fr_light_grey: Palette.fr_light_grey,
  lineColor: Palette.underlineColor,
  otp_card: Palette.card_color,
  in_a_tab_color: Palette.tab_theme_1,
  a_tab_color: Palette.tab_theme_2,
  disable_color: Palette.disable_color,
  subheader_color: Palette.subheader_color,
  red_color: Palette.pdfRed,
  text_color: Palette.text_color,
  background_light_grey: Palette.bg_light_grey,
  toptabcolor: Palette.toptabcolor,
  lightgray: Palette.lightgray,
  light_white: Palette.dim_color,
  blank_color: Palette.backgroundGrey,
  light_green: Palette.light_green,
  me_chat_color: Palette.light_grey_c,
  rating_color: Palette.gold_color,
  light_blue: Palette.light_blue,
  feedback_color: Palette.light_green_light,
  dark_color: Palette.o_black,
  t_green: Palette.t_green,
  lightTextgrey: Palette.lightTextgrey,
  placeHolderColor: Palette.placeHolderColor,
  button_color: Palette.button_color,
  light_grey_background: Palette.light_grey_background,
  textGreyColor: Palette.textGreyColor,
  border_color: Palette.dim_color,
  field_background: Palette.field_background,
  buttonColor: Palette.buttonColor,
  titleColor: Palette.titleColor,
  white: Palette.white,
  lightGray: Palette.lightGray,
  darkGray: Palette.darkGray,
  borderWidthColor: Palette.borderWidthColor,
  errorColor: Palette.red_color,
  recorrection_color: Palette.light_red,
  border_dark_grey: Palette.border_dark_grey,
  task_card_background: Palette.task_card_background,
  task_card_border: Palette.task_card_border,
  description_gray: Palette.description_gray,
  dark_grey: Palette.dark_grey,
  error_red: Palette.error_red,
  error_light_red: Palette.error_light_red,
  error_pink_background: Palette.error_pink_background,
  drawer_border_color: Palette.drawer_border_color,
  drop_down_icon: Palette.drop_down_icon,
  modal_background_color: Palette.modal_background_color,
  radio_button_color: Palette.radio_button_color,
  form_header_color_light: Palette.cardGrey,
  text_color_dark: Palette.text_color_dark,
  previous_button_color: Palette.previous_button_color,
  clear_icon_color: Palette.clear_icon_color,
  button_disable_color: Palette.dim_color,
  form_header_color: Palette.light_blue,
  text_color_light: Palette.text_color_light,
  text_color_darker: Palette.text_color_darker,
};

export default Colors;
